### ISSUE TITLE
adding support for `type` argument

### ISSUE THREAD

**Issue by IndrajeetPatil** [sbalci/jjstatsplot#3]
Most functions in `ggstatsplot` have this argument and it would be good to support it in `jjstatsplot`:

![image](https://user-images.githubusercontent.com/11330453/98530892-d1253680-227f-11eb-8775-8bc0c057d9fe.png)

**Comment by sbalci** [comment]
Thank you very much.
You are right. It is important for users. I was thinking of adding a test to guide the user which method is appropriate. But until that time I will add the argument.
By the way jamovi is using mran snapshots so it still uses ggstatsplot 0.5. I tried to add ggstatsplot from github but then the dependencies were not compatible. That is why some updates come later.

**Comment by IndrajeetPatil** [comment]
No worries, just thought I would have a reminder in the form of an issue :)

**Comment by sbalci** [comment]
Dear @IndrajeetPatil 
I have started adding type arguments
for `gghistostats` when using `type = "np"` I get following error. Others work fine.

```r
Debug

Error in signif(CI1, digits = digits): Nicht-numerisches Argument für mathematische Funktion

eval(ev)
eval(ev)
private$.plot(image, theme = t$theme, ggtheme = t$ggtheme, ...)
ggstatsplot::gghistostats(data = mydata, x = !!dep, type = typestatistics, ggtheme = ggplot2::theme_bw(), ggstatsplot.layer = TRUE, )
statsExpressions::expr_t_onesample(data = df, x = {
    {
        x
    }
}, type = type, test.value = test.value, bf.prior = bf.prior, robust.estimator = "onestep", effsize.type = effsize.type, conf.type = "norm", conf.level = conf.level, nboot = nboot, k = k, messages = messages)
rcompanion::wilcoxonOneSampleR(x = data %>% dplyr::pull({
    {
        x
    }
}), mu = test.value, ci = TRUE, conf = conf.level, type = conf.type, R = nboot, histogram = FALSE, digits = k, reportIncomplete = TRUE) %>% rcompanion_cleaner(.)
eval(lhs, parent, parent)
eval(lhs, parent, parent)
rcompanion::wilcoxonOneSampleR(x = data %>% dplyr::pull({
    {
        x
    }
}), mu = test.value, ci = TRUE, conf = conf.level, type = conf.type, R = nboot, histogram = FALSE, digits = k, reportIncomplete = TRUE)
```
