### ISSUE TITLE
Graph labels x-axis

### ISSUE THREAD

**Issue by scro1461** [sbalci/jjstatsplot#4]
Its is possible to add an option to0 that allows the user to rotate the labels. For longer labels, the text overlaps
<img width="806" alt="Screenshot 2021-12-21 at 09 44 04" src="https://user-images.githubusercontent.com/9356075/146908147-f876045d-e1d2-4a83-947d-3a1a5e904960.png">
.

**Comment by sbalci** [comment]
Thank you for the suggestion. I will try to update soon.
