### ISSUE TITLE
Version of jjstatsplot for jamovi 2.3.

### ISSUE THREAD

**Issue by ravellom** [sbalci/jjstatsplot#5]
Hi, I'm a user of the excellent and very useful jjstatsplot module, but I haven't been able to use it anymore after upgrading to 2.3.
When will the version of jjstatsplot compatible with jamovi 2.3 be available?
Thank you in advance for your response and congratulations for your commendable work.

**Comment by sbalci** [comment]
Hi, Thank you.
I am working on it. Will be available in a couple of days.
